-- ============================================================
-- PAD_IPD — Asociaciones Deportivas (72 organizations)
-- Source: Juntas_Directivas__20252028_17.xlsx
-- Version: 1.0 | Date: 2026-03-17
-- ============================================================

USE PAD_IPD;
GO

INSERT INTO pad.Asociacion_Deportiva (nombre, nombre_formal, tipo_organizacion, es_grupo_trabajo) VALUES
('ACTIVIDADES SUBACUÁTICAS', 'Federación Deportiva Peruana de Actividades Subacuáticas', 'FEDERACION', 0),
('AERODEPORTIVA', NULL, 'FEDERACION', 0),
('AJEDREZ', 'Federación Deportiva Peruana de Ajedrez', 'FEDERACION', 0),
('ANPPERÚ', 'Asociación Nacional Paralímpica del Perú', 'ASOCIACION', 0),
('ATLETISMO', 'Federación Deportiva Peruana de Atletismo', 'FEDERACION', 0),
('AUTOMOVILISMO', 'Federación Peruana de Automovilismo Deportivo', 'FEDERACION', 0),
('BÁDMINTON', 'Federación Deportiva Peruana de Bádminton', 'FEDERACION', 0),
('BASKETBALL', NULL, 'FEDERACION', 0),
('BÉISBOL', 'Federación Deportiva Peruana de Béisbol', 'FEDERACION', 0),
('BILLAR', 'Federación Deportiva Peruana de Billar', 'FEDERACION', 0),
('BOCHAS', 'Federación Deportiva Peruana de Bochas', 'FEDERACION', 0),
('BOWLING', 'Federación Peruana de Bowling', 'FEDERACION', 0),
('BOXEO', 'Federación Deportiva Peruana de Boxeo', 'FEDERACION', 0),
('CANOTAJE', 'Federación Deportiva Nacional de Canotaje', 'FEDERACION', 0),
('CAPOEIRA', 'Federación Deportiva Nacional Peruana de Capoeira', 'FEDERACION', 0),
('CICLISMO', 'Federación Deportiva Nacional Peruana de Ciclismo', 'FEDERACION', 0),
('CRICKET', 'Federación Deportiva Nacional Peruana de Cricket', 'FEDERACION', 0),
('DEPORTES ACUÁTICOS', 'Federación Deportiva Nacional de Deportes Acuáticos', 'FEDERACION', 0),
('DEPORTES ELECTRÓNICOS', 'Federación Deportiva Peruana de Deportes Electrónicos', 'FEDERACION', 0),
('ECUESTRE', 'Federación Deportiva Nacional Ecuestre', 'FEDERACION', 0),
('ESCALADA', 'Federación Deportiva Peruana de Escalada', 'FEDERACION', 0),
('ESGRIMA', 'Federación Deportiva Nacional Peruana de Esgrima', 'FEDERACION', 0),
('ESQUÍ ACUÁTICO', 'Federación Peruana de Esquí Acuático', 'FEDERACION', 0),
('FEDENADIF', 'Federación Deportiva Nacional de Personas con Discapacidad Física', 'FEDERACION', 0),
('FEDEPEDI', 'Federación Deportiva Peruana de Personas con Discapacidad Intelectual', 'FEDERACION', 0),
('FEDUP', 'Federación Deportiva Universitaria del Perú', 'FEDERACION', 0),
('FISICOCULTURISMO', 'Federación Deportiva Nacional de Fisicoculturismo y Fitness', 'FEDERACION', 0),
('FÚTBOL AMERICANO', 'Federación de Fútbol Americano', 'FEDERACION', 1),
('GIMNASIA', 'Federación Deportiva Peruana de Gimnasia', 'FEDERACION', 0),
('GOLF', 'Federación Deportiva Nacional Peruana de Golf', 'FEDERACION', 0),
('HANDBALL', 'Federación Deportiva Peruana de Handball', 'FEDERACION', 0),
('HOCKEY', 'Federación Deportiva Peruana de Hockey', 'FEDERACION', 0),
('JIU JITSU', NULL, 'FEDERACION', 0),
('JUDO', 'Federación Deportiva Peruana de Judo', 'FEDERACION', 0),
('KARATE', 'Federación Deportiva Peruana de Karate', 'FEDERACION', 1),
('KARTISMO', 'Federación Deportiva Peruana de Kartismo', 'FEDERACION', 0);
GO

INSERT INTO pad.Asociacion_Deportiva (nombre, nombre_formal, tipo_organizacion, es_grupo_trabajo) VALUES
('KENDO', 'Federación Deportiva Nacional de Kendo del Perú', 'FEDERACION', 0),
('KICK BOXING', 'Federación Deportiva Peruana de Kickboxing y Deportes de Contacto', 'FEDERACION', 0),
('KUNG FU', 'Federación Deportiva Peruana de Kung Fu', 'FEDERACION', 0),
('LEVANTAMIENTO DE PESAS', 'Federación Deportiva Peruana de Levantamiento de Pesas', 'FEDERACION', 0),
('LEVANTAMIENTO DE POTENCIA', 'Federación Deportiva Nacional de Levantamiento de Potencia', 'FEDERACION', 0),
('LUCHA AMATEUR', 'Federación Deportiva Peruana de Lucha Amateur', 'FEDERACION', 0),
('LUCHA DE BRAZOS', 'Federación Deportiva Nacional Peruana de Lucha de Brazos', 'FEDERACION', 0),
('MOTOCICLISMO', 'Federación Deportiva Peruana de Motociclismo', 'FEDERACION', 0),
('MOTONÁUTICA', NULL, 'FEDERACION', 0),
('MUAY THAI', 'Federación Deportiva Peruana de Muay Thai', 'FEDERACION', 0),
('PALETA FRONTÓN', 'Federación Deportiva Peruana de Paleta Frontón', 'FEDERACION', 0),
('PATINAJE', 'Federación Deportiva Nacional Peruana de Patinaje', 'FEDERACION', 0),
('PATINAJE SOBRE HIELO', 'Federación Peruana de Patinaje sobre Hielo', 'FEDERACION', 0),
('PENTATLÓN MODERNO', 'Federación Deportiva Peruana de Pentatlón Moderno', 'FEDERACION', 0),
('PICKLEBALL', 'Federación Deportiva Nacional de Pickleball', 'FEDERACION', 0),
('POLICÍAS Y BOMBEROS', 'Federación Deportiva Peruana de Policías y Bomberos', 'FEDERACION', 0),
('POLO', NULL, 'FEDERACION', 0),
('REMO', 'Federación Peruana de Remo', 'FEDERACION', 0),
('RUGBY', 'Federación Peruana de Rugby', 'FEDERACION', 0),
('RUGBY EN SILLA DE RUEDAS', 'Federación Deportiva Nacional de Rugby en Silla de Ruedas', 'FEDERACION', 0),
('SÍNDROME DE DOWN', 'Federación Deportiva Nacional de Personas con Síndrome de Down', 'FEDERACION', 0),
('SOFTBOL', 'Federación Deportiva Nacional Peruana de Softbol', 'FEDERACION', 0),
('SPORTING CLAYS', 'Federación Deportiva Nacional Sporting Clays Peruana', 'FEDERACION', 0),
('SQUASH RACKET', 'Federación Peruana de Squash Racket', 'FEDERACION', 0),
('TABLA', 'Federación Deportiva Nacional de Tabla - FENTA', 'FEDERACION', 0),
('TAE KWON DO', 'Federación Deportiva Peruana de Tae Kwon Do', 'FEDERACION', 0),
('TENIS', 'Federación Deportiva Peruana de Tenis', 'FEDERACION', 0),
('TENIS DE MESA', 'Federación Deportiva Peruana de Tenis de Mesa', 'FEDERACION', 0),
('TIRO', 'Federación Deportiva Nacional de Tiro Peruana', 'FEDERACION', 0),
('TIRO CON ARCO', 'Federación Deportiva Peruana de Tiro con Arco', 'FEDERACION', 0),
('TRIATLÓN', 'Federación Deportiva Nacional de Triatlón', 'FEDERACION', 0),
('VA''A', 'Federación Deportiva Peruana de Va''a', 'FEDERACION', 0),
('VELA', 'Federación Deportiva Nacional Peruana de Vela', 'FEDERACION', 0),
('VOLEIBOL', 'Federación Peruana de Voleibol', 'FEDERACION', 0),
('FÚTBOL', 'Federación Peruana de Fútbol', 'FEDERACION', 0),
('COP', 'Comité Olímpico Peruano', 'COMITE', 0);
GO
